/**
 * Ambient interaction picking — fully manifest-driven.
 *
 * The kernel's AmbianceManager calls these to decide how to "interact"
 * with an open widget. Candidate actions come from the widget
 * definition's `accepts` entries that carry a `simulate` hint — the
 * kernel knows no widget vocabulary. Params (e.g. a sticky color) are
 * pre-generated by the hint so cursor theater and widget state agree.
 */
import type { AmbianceMirrorPolicy, WidgetSimulationIntentPayload, WidgetSimulationIntentSeed } from '../contracts/socket.js'
import type { WidgetActionDescriptor, WidgetDefinition } from '../contracts/widget.js'
import { WIDGET_DEFINITIONS } from '../widgets/index.js'

/** Legacy Application ids that map onto a definition-backed widget. */
const WIDGET_ID_ALIASES: Record<string, string> = {
  browser: 'gallery',
  spotify: 'music',
}

function resolveDefinition(widgetId: string): WidgetDefinition | undefined {
  const id = WIDGET_ID_ALIASES[widgetId] ?? widgetId
  return WIDGET_DEFINITIONS.find((d) => d.id === id)
}

function simulatableActions(def: WidgetDefinition): WidgetActionDescriptor[] {
  return def.accepts.filter((a) => a.simulate)
}

export function getAmbianceInteractMirrorPolicy(widgetId: string): AmbianceMirrorPolicy {
  const def = resolveDefinition(widgetId)
  return def && simulatableActions(def).length > 0 ? 'shared-safe' : 'unsafe-requires-runtime-event'
}

export function pickAmbianceInteractionIntent(widgetId: string): WidgetSimulationIntentSeed | null {
  const def = resolveDefinition(widgetId)
  if (!def) return null

  const actions = simulatableActions(def)
  if (!actions.length) return null

  const weights = actions.map((a) => (typeof a.simulate === 'object' ? Math.max(0.01, a.simulate.weight ?? 1) : 1))
  const totalWeight = weights.reduce((sum, w) => sum + w, 0)
  let target = Math.random() * totalWeight
  let picked = actions[actions.length - 1]
  for (let i = 0; i < actions.length; i++) {
    target -= weights[i]
    if (target <= 0) { picked = actions[i]; break }
  }

  const params = typeof picked.simulate === 'object' && picked.simulate.params
    ? picked.simulate.params()
    : undefined
  return { widgetId, kind: picked.action, ...(params ? { params } : {}) }
}

export function buildWidgetSimulationIntent(actionId: string, seed: WidgetSimulationIntentSeed): WidgetSimulationIntentPayload {
  return { ...seed, actionId }
}
