import type { AppConfig } from '../types/scene.js'
import { STATE, OVERLAY_EVENT } from '../types/state.js'

export const DEFAULT_CONFIG: AppConfig = {
  scenes: {
    LOBBY: {
      id: 'LOBBY',
      label: 'LOBBY',
      backgroundOpaque: true,
      // Lobby = 3D room (R3F ThreeBackground plugin — NOT the Win98 desktop).
      // The desktop layer is hidden in LOBBY state; only the 3D room renders here.
      sources: [],
      lobbyConfig: {
        ambientColor: '#1e1a3a',
        ambientIntensity: 0.28,
        fogColor: '#080810',
        fogNear: 6,
        fogFar: 22,
        wallColor: '#0f0f16',
        floorColor: '#0d0d14',
        floorReflectivity: 0.6,
        crtGlowColor: '#00c8e0',
        neonStrips: true,
        neonColors: ['#00c8ff', '#8000ff'],
        dustMotes: true,
        cameraFov: 62,
        starsCount: 400,
      },
    },

    DESKTOP: {
      id: 'DESKTOP',
      label: 'DESKTOP',
      backgroundOpaque: true,
      // Desktop = Win98 OS layer (shown via #desktop-layer CSS, not a source plugin).
      // Sources layer is empty — the desktop canvas owns this state visually.
      sources: [],
      style: {
        background: {
          type: 'gradient',
          color: '#000000',
          gradient: 'linear-gradient(135deg, #0c0c1e 0%, #1a0533 50%, #0c0c1e 100%)',
          imageUrl: '',
          videoUrl: '',
          pattern: 'none',
          opacity: 1,
          blur: 0,
        },
        effects: {
          crt: true,
          noise: false,
          vignette: true,
          flicker: false,
          chromatic: false,
          scanlineOpacity: 0.18,
          noiseOpacity: 0.06,
          vignetteStrength: 0.65,
        },
        particles: {
          enabled: false,
          preset: 'none',
          density: 0.5,
          speed: 0.4,
        },
        fontFamily: 'default',
        accentColor: '#00ff41',
        textColor: '#ffffff',
      },
    },
    GAMEPLAY: {
      id: 'GAMEPLAY',
      label: 'GAMEPLAY',
      backgroundOpaque: false,
      sources: [
        {
          id: 'gameplay-crt',
          pluginType: 'crt-effect',
          config: { scanlineIntensity: 0.12, flickerRate: 0.008, vignetteStrength: 0.2 },
          position: { x: 0, y: 0, width: 1920, height: 1080 },
          zIndex: 5,
          visible: true,
        },
      ],
    },
    TV: {
      id: 'TV',
      label: 'TV MODE',
      backgroundOpaque: true,
      sources: [
        {
          id: 'tv-bg',
          pluginType: 'image-slideshow',
          config: { source: 'scraped-games', interval: 4, transition: 'cut' },
          position: { x: 0, y: 0, width: 1920, height: 1080 },
          zIndex: 0,
          visible: true,
        },
        {
          id: 'tv-crt',
          pluginType: 'crt-effect',
          config: { scanlineIntensity: 0.5, flickerRate: 0.04, vignetteStrength: 0.65 },
          position: { x: 0, y: 0, width: 1920, height: 1080 },
          zIndex: 5,
          visible: true,
        },
        {
          id: 'tv-label',
          pluginType: 'text-widget',
          config: {
            content: '[ CHANNEL 2 — ON AIR ]',
            font: 'vt323',
            fontSize: 28,
            color: '#00ff88',
            typewriterMode: false,
          },
          position: { x: 40, y: 40, width: 500, height: 50 },
          zIndex: 10,
          visible: true,
        },
      ],
    },
    MUSIC: {
      id: 'MUSIC',
      label: 'MUSIC.exe',
      backgroundOpaque: true,
      sources: [
        {
          id: 'music-crt',
          pluginType: 'crt-effect',
          config: { scanlineIntensity: 0.3, flickerRate: 0.02, vignetteStrength: 0.4 },
          position: { x: 0, y: 0, width: 1920, height: 1080 },
          zIndex: 5,
          visible: true,
        },
        {
          id: 'music-label',
          pluginType: 'text-widget',
          config: {
            content: 'MUSIC.exe — LOADING...',
            font: 'vt323',
            fontSize: 36,
            color: '#ffaa00',
            typewriterMode: true,
          },
          position: { x: 760, y: 500, width: 400, height: 60 },
          zIndex: 10,
          visible: true,
        },
      ],
    },
    ARCHIVE: {
      id: 'ARCHIVE',
      label: 'ARCHIVE.exe',
      backgroundOpaque: true,
      sources: [
        {
          id: 'archive-crt',
          pluginType: 'crt-effect',
          config: { scanlineIntensity: 0.3, flickerRate: 0.02, vignetteStrength: 0.4 },
          position: { x: 0, y: 0, width: 1920, height: 1080 },
          zIndex: 5,
          visible: true,
        },
        {
          id: 'archive-label',
          pluginType: 'text-widget',
          config: {
            content: 'ARCHIVE.exe — READING MEMORY...',
            font: 'vt323',
            fontSize: 36,
            color: '#00aaff',
            typewriterMode: true,
          },
          position: { x: 660, y: 500, width: 600, height: 60 },
          zIndex: 10,
          visible: true,
        },
      ],
    },
  },

  applications: [
    {
      id: 'battlefield6',
      label: 'Battlefield6.exe',
      icon: '🎮',
      appType: 'scene' as const,
      targetSceneId: STATE.GAMEPLAY,
      transitionType: 'desktop-to-gameplay',
      introTransition: 'desktop-to-gameplay',
      exitTransition: 'gameplay-to-desktop',
      iconPosition: { x: 16, y: 16 },
      iconSize: 'normal' as const,
    },
    {
      id: 'tv',
      label: 'TV.exe',
      icon: '📺',
      appType: 'scene' as const,
      targetSceneId: STATE.TV,
      transitionType: 'desktop-to-tv',
      introTransition: 'desktop-to-tv',
      exitTransition: 'tv-to-desktop',
      iconPosition: { x: 16, y: 110 },
      iconSize: 'normal' as const,
    },
    {
      id: 'spotify',
      label: 'Spotify.exe',
      icon: '🎵',
      appType: 'widget' as const,
      targetSceneId: STATE.MUSIC,
      transitionType: 'default',
      iconPosition: { x: 16, y: 204 },
      iconSize: 'normal' as const,
    },
    {
      id: 'chat',
      label: 'Chat.exe',
      icon: '💬',
      appType: 'widget' as const,
      targetSceneId: STATE.MUSIC,
      transitionType: 'default',
      iconPosition: { x: 16, y: 298 },
      iconSize: 'normal' as const,
    },
    {
      id: 'browser',
      label: 'Browser.exe',
      icon: '🌐',
      appType: 'widget' as const,
      targetSceneId: STATE.DESKTOP,
      transitionType: 'default',
      iconPosition: { x: 16, y: 392 },
      iconSize: 'normal' as const,
    },
    {
      id: 'archive',
      label: 'Archive.exe',
      icon: '📁',
      appType: 'widget' as const,
      targetSceneId: STATE.ARCHIVE,
      transitionType: 'default',
      iconPosition: { x: 16, y: 486 },
      iconSize: 'normal' as const,
    },
  ],

  keybinds: {
    obs: {
      F1: 'scene:gameplay',
      F2: 'overlay:death',
      F3: 'overlay:revive',
      F4: 'overlay:victory',
      F5: 'scene:tv',
      F6: 'scene:desktop',
      F7: 'scene:lobby',
      Escape: 'panic',
    },
    admin: {
      F1: 'scene:gameplay',
      F2: 'overlay:death',
      F3: 'overlay:revive',
      F4: 'overlay:victory',
      F5: 'scene:tv',
      F6: 'scene:desktop',
      F7: 'scene:lobby',
      Escape: 'panic',
    },
  },

  obs: {
    url: 'ws://localhost:4455',
    password: '',
  },

  audio: {
    masterVolume: 0.8,
    sfxVolume: 0.7,
    musicVolume: 0.4,
  },

  overlayStyle: {
    background: {
      type: 'gradient',
      color: '#000000',
      gradient: 'linear-gradient(135deg, #0c0c1e 0%, #1a0533 50%, #0c0c1e 100%)',
      imageUrl: '',
      videoUrl: '',
      pattern: 'none',
      opacity: 1,
      blur: 0,
    },
    effects: {
      crt: true,
      noise: false,
      vignette: true,
      flicker: false,
      chromatic: false,
      scanlineOpacity: 0.18,
      noiseOpacity: 0.06,
      vignetteStrength: 0.65,
    },
    particles: {
      enabled: false,
      preset: 'none',
      density: 0.5,
      speed: 0.4,
    },
    fontFamily: 'default',
    accentColor: '#00ff41',
    textColor: '#ffffff',
  },

  desktopConfig: {
    defaultIconSize: 'normal',
    autoArrangeIcons: false,
    screenSaver: {
      enabled: false,
      timeoutMinutes: 5,
      preset: 'starfield',
    },
    systemSounds: {
      startup: '',
      error: '',
      notify: '',
      click: '',
      close: '',
    },
  },

  events: [
    { id: OVERLAY_EVENT.DEATH,          label: 'DEATH',    icon: '💀', color: 'text-red-400',     desc: 'Red vignette + YOU DIED',           effects: [{ type: 'death-overlay',   cfg: {} }],                                                                                             auto: { enabled: false, mode: 'interval', intervalMin: 20, idleMin: 5 } },
    { id: OVERLAY_EVENT.VICTORY,        label: 'VICTORY',  icon: '🏆', color: 'text-yellow-400',  desc: 'Win98 dialog: MISSION.LOG saved',   effects: [{ type: 'victory-overlay', cfg: {} }],                                                                                             auto: { enabled: false, mode: 'interval', intervalMin: 30, idleMin: 5 } },
    { id: OVERLAY_EVENT.REVIVE,         label: 'REVIVE',   icon: '❤',  color: 'text-emerald-400', desc: 'Terminal: Restarting process...',   effects: [{ type: 'revive-overlay',  cfg: {} }],                                                                                             auto: { enabled: false, mode: 'interval', intervalMin: 25, idleMin: 5 } },
    { id: OVERLAY_EVENT.NETWORK_GLITCH, label: 'GLITCH',   icon: '📡', color: 'text-purple-400',  desc: 'Full-screen artifact burst',        effects: [{ type: 'network-glitch',  cfg: { message: '[ NETWORK INTERRUPTION ]', duration: 2 } }],                                          auto: { enabled: false, mode: 'interval', intervalMin: 15, idleMin: 5 } },
    { id: 'idle-floaties',              label: 'FLOATIES', icon: '✨',  color: 'text-cyan-400',    desc: 'Glowing symbols drift over screen', effects: [{ type: 'floaties',         cfg: { count: 10, duration: 10, speed: 1.0 } }],                                                     auto: { enabled: false, mode: 'idle',     intervalMin: 15, idleMin: 5 } },
  ],
}
