/**
 * Kernel → Userspace signals.
 *
 * These are directives the kernel sends to overlay clients. The overlay reacts
 * to them but never blocks the kernel. Adding a signal here means adding one
 * entry to the overlay's signalMap.ts.
 *
 * Direction: server emits → client listens
 */

import type { Rect } from '../domain/geometry.js'
import type { STATE } from './state.js'
import type { AppConfig } from '../domain/config.js'
import type { RTCIceCandidateInit } from './webrtc-types.js'
import type { DesktopConfig } from '../domain/desktop.js'
import type { DesktopAmbianceConfig } from '../domain/ambiance.js'
import type { WidgetLayoutItem } from '../domain/application.js'
import type { TransitionStep } from '../domain/scene.js'
import type { OverlayTriggerPayload } from './effects.js'
import type { ObsStatusPayload, RuntimeDiagnosticsPayload } from './diagnostics.js'

// ── BusFrame (shared type for bus trace tooling) ──────────────────

export interface BusFrame {
  /** Name of the event being sent over the bus. */
  event: string
  /** Event payload; shape depends on the specific event. */
  payload: unknown
  /** Optional origin of the event, such as a subsystem or client. */
  source?: string
  /** Timestamp when the frame was created, in milliseconds. */
  t: number
  /** Monotonic sequence number used for ordering frames. */
  seq: number
}

// ── Manager signal payloads ────────────────────────────────────────

export interface ChatMessagePayload {
  user: string
  text: string
  color: string
  badges: string[]
  channel: string
  source: 'twitch' | 'simulation'
}

export interface TwitchFollowPayload {
  user: string
  userId: string
}

export interface TwitchSubscribePayload {
  user: string
  userId: string
  tier: string
  isGift: boolean
}

export interface TwitchGiftSubPayload {
  gifter: string
  gifterId: string
  tier: string
  total: number
  cumulative?: number
}

export interface TwitchCheerPayload {
  user: string
  userId?: string
  bits: number
  message: string
  isAnonymous: boolean
}

export interface TwitchRaidPayload {
  from: string
  fromId: string
  viewers: number
}

export interface TwitchPointsRedemptionPayload {
  user: string
  userId: string
  rewardId: string
  rewardTitle: string
  input: string
}

export interface TwitchStreamOnlinePayload {
  startedAt: string
}

export interface TwitchHypeTrainBeginPayload {
  level: number
  total: number
  goal: number
}

export interface TwitchHypeTrainEndPayload {
  level: number
  total: number
}

export interface TwitchEventSubConnectedPayload {
  sessionId: string
}

export interface ShowStepPayload {
  showId: string
  stepIndex: number
  label: string
}

// ── Re-exported payload types ─────────────────────────────────────

export type { ObsStatusPayload, RuntimeDiagnosticsPayload }

// ── Transition payload ────────────────────────────────────────────

/** Shape of the transition:play signal */
export interface TransitionPlayPayload {
  from: STATE
  to: STATE
  /** Ordered exit pipeline — plays before scene content swaps */
  exit: TransitionStep[]
  /** Ordered intro pipeline — plays after scene content swaps */
  intro: TransitionStep[]
}

// ── Desktop signal payloads ───────────────────────────────────────

export interface DesktopNotificationPayload {
  title: string
  body: string
  icon?: string
  durationMs?: number
}

export interface DesktopRecycleBinPayload {
  full: boolean
}

export interface DesktopScreenSaverPreviewPayload {
  preset: DesktopConfig['screenSaver']['preset']
}

export interface DesktopStartMenuStatePayload {
  open: boolean
  activeRoot: 'programs' | 'widget-layouts' | 'layouts' | 'scenes' | null
}

export type DesktopStartMenuRoot = 'programs' | 'widget-layouts' | 'layouts' | 'scenes' | null

// Start-menu simulation phases, cursor mirroring, and menu timelines are
// overlay presentation concerns — their types live in the overlay
// (desktop/simulationTypes.ts), not in the kernel ABI.

// ── Desktop drag/resize signal payloads ───────────────────────────

export interface DesktopIconDragPayload {
  appId: string
  x: number
  y: number
  phase: 'start' | 'move' | 'end'
}

export interface DesktopWidgetDragPayload {
  widgetId: string
  x: number
  y: number
  phase: 'start' | 'move' | 'end'
}

export interface DesktopWidgetResizePayload extends Rect {
  widgetId: string
  phase: 'start' | 'move' | 'end'
}

// ── Ambiance signal payloads ──────────────────────────────────────

export type AmbianceMirrorPolicy = 'shared-safe' | 'leader-only' | 'unsafe-requires-runtime-event'

export interface WidgetSimulationCommandPayload {
  widgetId: string
  action: 'open' | 'close' | 'toggle'
}

/**
 * Generic widget simulation intent. `kind` is an action id from the
 * widget's manifest `accepts` (e.g. 'gallery:next'); `params` carries
 * values pre-generated by the action's `simulate.params` hint (e.g. a
 * sticky color) so cursor theater and widget state agree. The kernel
 * carries these opaquely — it knows no widget vocabulary.
 */
export interface WidgetSimulationIntentPayload {
  actionId: string
  widgetId: string
  kind: string
  params?: Record<string, unknown>
}

export type WidgetSimulationIntentSeed = Omit<WidgetSimulationIntentPayload, 'actionId'>

export interface AmbianceSimulationPayload {
  actionId: string
  /** Target ID — widget ID for widget actions, layout ID or scene ID for select actions. */
  widgetId: string
  action: 'open' | 'close' | 'interact' | 'select'
  /** Discriminates the target type. Absent means 'widget' for backward compatibility. */
  targetKind?: 'widget' | 'layout' | 'scene'
  /** Explicit start-menu navigation path for layout/scene select actions, e.g. ['Layouts', 'My Layout']. */
  menuPath?: string[]
  mirrorPolicy: AmbianceMirrorPolicy
  sharedIntent: WidgetSimulationIntentPayload | null
}

// ── Kernel signal fabric ──────────────────────────────────────────
//
// Domain events (integrations, sequencers, chat) are NOT bespoke socket
// events. They travel kernel → clients inside a single generic
// 'kernel:signal' channel carrying BusFrame envelopes. This map is the
// single source of truth for which KernelBus events are public and what
// their payloads look like — the server's KernelEvents interface extends
// it, the forwarder allowlists by its keys, and clients narrow payloads
// through it (overlay: onKernelSignal helper).
//
// Adding a public manager event = add ONE entry here (+ its flag below,
// compiler-enforced). Zero transport changes.

export interface KernelSignalMap {
  'chat:message': ChatMessagePayload
  'chat:connected': { channel: string }
  'twitch:eventsub:connected': TwitchEventSubConnectedPayload
  'twitch:follow': TwitchFollowPayload
  'twitch:subscribe': TwitchSubscribePayload
  'twitch:gift-sub': TwitchGiftSubPayload
  'twitch:cheer': TwitchCheerPayload
  'twitch:raid': TwitchRaidPayload
  'twitch:points:redemption': TwitchPointsRedemptionPayload
  'twitch:stream:online': TwitchStreamOnlinePayload
  'twitch:stream:offline': Record<string, never>
  'twitch:hype-train:begin': TwitchHypeTrainBeginPayload
  'twitch:hype-train:end': TwitchHypeTrainEndPayload
  'obs:stream:started': Record<string, never>
  'obs:stream:stopped': Record<string, never>
  'obs:recording:started': Record<string, never>
  'obs:recording:stopped': Record<string, never>
  'obs:virtualcam:changed': { active: boolean }
  'show:step': ShowStepPayload
}

export type KernelSignalEvent = keyof KernelSignalMap

/** Total record — adding a KernelSignalMap entry fails compilation until
 *  its flag exists here, and vice versa. Keeps map and allowlist in sync. */
const PUBLIC_KERNEL_SIGNAL_FLAGS: Record<KernelSignalEvent, true> = {
  'chat:message': true,
  'chat:connected': true,
  'twitch:eventsub:connected': true,
  'twitch:follow': true,
  'twitch:subscribe': true,
  'twitch:gift-sub': true,
  'twitch:cheer': true,
  'twitch:raid': true,
  'twitch:points:redemption': true,
  'twitch:stream:online': true,
  'twitch:stream:offline': true,
  'twitch:hype-train:begin': true,
  'twitch:hype-train:end': true,
  'obs:stream:started': true,
  'obs:stream:stopped': true,
  'obs:recording:started': true,
  'obs:recording:stopped': true,
  'obs:virtualcam:changed': true,
  'show:step': true,
}

export const PUBLIC_KERNEL_SIGNALS = Object.keys(PUBLIC_KERNEL_SIGNAL_FLAGS) as KernelSignalEvent[]

const PUBLIC_KERNEL_SIGNAL_SET: ReadonlySet<string> = new Set(PUBLIC_KERNEL_SIGNALS)

export function isPublicKernelSignal(event: string): event is KernelSignalEvent {
  return PUBLIC_KERNEL_SIGNAL_SET.has(event)
}

// ── Runtime config ────────────────────────────────────────────────

export interface RuntimeConfig {
  desktopConfig?: Pick<Partial<DesktopConfig>, 'globalThemeDefault' | 'widgetThemes' | 'iconAnimation' | 'iconMotion' | 'iconArrangement' | 'iconArrangementMotion' | 'screenSaver'>
  /** Transient per-widget positions (not persisted — runtime state only) */
  widgetPositions?: Record<string, { x: number; y: number }>
  /** Transient per-widget sizes (not persisted — runtime state only) */
  widgetSizes?: Record<string, { width?: number; height?: number }>
  /** Transient per-widget z-indices (not persisted — runtime state only) */
  widgetZIndices?: Record<string, number>
  desktopAmbiance?: Partial<DesktopAmbianceConfig>
}

// ── ServerToClientEvents (signals) ───────────────────────────────

/**
 * Signals the kernel sends to overlay/admin clients.
 * Client hooks register `socket.on(...)` for these.
 */
export interface ServerToClientEvents {
  /** Scene state changed — overlay updates its visual state */
  'state:update': (payload: { state: STATE; previousState: STATE }) => void
  /** Transition pipeline to play before/after scene swap */
  'transition:play': (payload: TransitionPlayPayload) => void
  /** One-shot effect/overlay trigger (effects, SFX) */
  'overlay:show': (payload: OverlayTriggerPayload) => void
  /** Full config replaced — re-render everything */
  'config:update': (config: AppConfig) => void
  /** Partial config update — merge into existing config */
  'config:patch': (updates: Partial<AppConfig>) => void
  /** OBS bridge connection status changed */
  'obs:status': (payload: ObsStatusPayload) => void
  /** Ambiance accept/reject counters updated */
  'ambiance:metrics': (payload: { accepted: number; rejected: number }) => void
  /** Periodic diagnostics snapshot from scheduler + ambiance managers */
  'runtime:diagnostics': (payload: RuntimeDiagnosticsPayload) => void
  /** Overlay slot ownership changed */
  'overlay:owner': (payload: { socketId: string | null }) => void
  /** Scoped runtime config applied */
  'runtime:config': (payload: RuntimeConfig) => void
  /** Ambiance manager wants the overlay to simulate a widget action */
  'ambiance:simulate': (payload: AmbianceSimulationPayload) => void
  /** Full state resync requested (e.g. after reconnect) */
  'overlay:resync': (payload: { reason: string }) => void
  /** Overlay slot rejected — already taken */
  'overlay:rejected': (payload: { reason: string }) => void
  /** Kernel wants a specific widget interaction (e.g. gallery:next) */
  'widget:simulate:intent': (payload: WidgetSimulationIntentPayload) => void
  /** Toggle a widget open/closed */
  'widget:toggle': (widgetId: string) => void
  /** Apply a named layout preset */
  'widget:layout:apply': (layoutId: string) => void
  /** Apply raw layout items */
  'widget:layout:apply:items': (items: WidgetLayoutItem[]) => void
  /** OS-style desktop notification */
  'desktop:notify': (payload: DesktopNotificationPayload) => void
  /** Recycle bin fill state changed */
  'desktop:recycle-bin': (payload: DesktopRecycleBinPayload) => void
  /** Start menu visibility / active root changed */
  'desktop:start-menu:state': (payload: DesktopStartMenuStatePayload) => void
  /** Screen saver preview command */
  'desktop:screen-saver:test': (payload: DesktopScreenSaverPreviewPayload) => void
  /** Widget wire triggered a widget action */
  'widget:chain:action': (payload: { targetWidgetId: string; action: string; sourceSignal: unknown }) => void
  /** Server-produced widget-style signal (signal:emit automation action) — overlay re-enters it on the DOM bus */
  'widget:signal': (payload: { source: string; event: string; payload: unknown }) => void
  /** Generic domain-event channel — BusFrame envelopes for every public
   *  KernelBus event (see KernelSignalMap). Clients subscribe via a typed
   *  helper (overlay: onKernelSignal) instead of bespoke socket events. */
  'kernel:signal': (frame: BusFrame) => void
  /** Bus trace frames batch (for dev tooling subscribers) */
  'bus:trace:frames': (frames: BusFrame[]) => void
  /** POV relay: SDP offer from server to overlay for active participant stream */
  'pov-online:relay:offer': (payload: { sdp: string }) => void
  /** POV relay: ICE candidate from server to overlay */
  'pov-online:relay:ice': (candidate: RTCIceCandidateInit) => void
}
