export { configRoute } from './config.js'
export { mediaRoute } from './media.js'
export { archiveRoute } from './archive.js'
export { roomRoute } from './room.js'
export { automationRoute } from './automation.js'
