import type { CameraFeed, CameraConnectionStatus } from '@ieom/shared'
import crypto from 'node:crypto'

/**
 * Input for registering a new camera feed.
 * Omits fields that are auto-generated by the registry.
 */
export type CameraFeedRegistration = Omit<
  CameraFeed,
  'id' | 'connectionStatus' | 'connectedAt' | 'registeredAt' | 'lastHealthCheck' | 'activityScore'
>

/**
 * Result of a registration attempt — either a valid CameraFeed or an error.
 */
export type RegistrationResult = CameraFeed | { error: string }

/**
 * CameraRegistry interface as defined in the design document.
 * Tracks all registered camera feeds and their runtime metadata in memory.
 */
export interface ICameraRegistry {
  readonly feeds: Map<string, CameraFeed>
  readonly maxConnections: number

  register(feed: CameraFeedRegistration): RegistrationResult
  unregister(feedId: string): boolean
  updateStatus(feedId: string, status: CameraConnectionStatus): void
  updateActivityScore(feedId: string, score: number): void
  getActiveFeed(feedId: string): CameraFeed | undefined
  getAllFeeds(): CameraFeed[]
  getConnectedFeeds(): CameraFeed[]
  findByAddress(address: string): CameraFeed | undefined
}

/**
 * In-memory Camera Registry that tracks runtime state of camera feeds.
 *
 * Responsibilities:
 * - Register/unregister camera feeds with UUID generation
 * - Validate labels (max 32 characters)
 * - Enforce capacity limits (configurable maxConnections, 3-10 range)
 * - Track connection status and activity scores per feed
 */
export class CameraRegistry implements ICameraRegistry {
  public readonly feeds: Map<string, CameraFeed> = new Map()
  public readonly maxConnections: number

  constructor(maxConnections: number = 10) {
    // Clamp maxConnections to the valid range of 3-10
    this.maxConnections = Math.max(3, Math.min(10, maxConnections))
  }

  /**
   * Register a new camera feed.
   *
   * - Generates a UUID for the feed
   * - Validates label length (max 32 chars)
   * - Checks capacity before adding
   * - Returns the created CameraFeed or an error object
   */
  register(input: CameraFeedRegistration): RegistrationResult {
    // Validate label length
    if (!input.label || input.label.length === 0) {
      return { error: 'label_required' }
    }

    if (input.label.length > 32) {
      return { error: 'label_too_long' }
    }

    // Check capacity
    if (this.feeds.size >= this.maxConnections) {
      return { error: 'capacity_reached' }
    }

    const feed: CameraFeed = {
      id: crypto.randomUUID(),
      label: input.label,
      obsAddress: input.obsAddress,
      obsPassword: input.obsPassword,
      sceneName: input.sceneName,
      connectionStatus: 'disconnected',
      connectedAt: null,
      registeredAt: Date.now(),
      lastHealthCheck: null,
      activityScore: 0,
    }

    this.feeds.set(feed.id, feed)
    return feed
  }

  /**
   * Unregister a camera feed by ID.
   * Returns true if the feed was found and removed, false otherwise.
   */
  unregister(feedId: string): boolean {
    return this.feeds.delete(feedId)
  }

  /**
   * Update the connection status of a feed.
   * Also updates connectedAt timestamp when status changes to 'connected'.
   */
  updateStatus(feedId: string, status: CameraConnectionStatus): void {
    const feed = this.feeds.get(feedId)
    if (!feed) return

    feed.connectionStatus = status

    if (status === 'connected') {
      feed.connectedAt = Date.now()
    }
  }

  /**
   * Update the activity score for a feed.
   * Score is clamped to [0, 1].
   */
  updateActivityScore(feedId: string, score: number): void {
    const feed = this.feeds.get(feedId)
    if (!feed) return

    feed.activityScore = Math.max(0, Math.min(1, score))
  }

  /**
   * Get a specific feed by ID.
   * Named getActiveFeed in the interface to match the design doc,
   * but functionally retrieves any feed by ID.
   */
  getActiveFeed(feedId: string): CameraFeed | undefined {
    return this.feeds.get(feedId)
  }

  /**
   * Get all registered feeds as an array.
   */
  getAllFeeds(): CameraFeed[] {
    return Array.from(this.feeds.values())
  }

  /**
   * Get only feeds with 'connected' status.
   */
  getConnectedFeeds(): CameraFeed[] {
    return Array.from(this.feeds.values()).filter(
      (feed) => feed.connectionStatus === 'connected'
    )
  }

  /**
   * Find a feed by its OBS WebSocket address.
   * Useful for reconnection detection (Requirement 1.3).
   */
  findByAddress(address: string): CameraFeed | undefined {
    for (const feed of this.feeds.values()) {
      if (feed.obsAddress === address) {
        return feed
      }
    }
    return undefined
  }
}
