/**
 * Loads the default AppConfig from the JSON fixtures at runtime.
 * Fixtures are generated by scripts/generate-fixtures.ts and committed to data/fixtures/.
 * This avoids bundling the large DEFAULT_CONFIG constant into the server at import time.
 */
import { readFileSync, existsSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import type { AppConfig } from '@ieomlabs/shared'
import { DEFAULT_CONFIG } from '@ieomlabs/shared'

const FIXTURE_PATH = join(dirname(fileURLToPath(import.meta.url)), '../../../../data/fixtures/default-config.json')

let _cached: AppConfig | null = null

/** Returns the default AppConfig, loaded from data/fixtures/default-config.json or falling back to shared DEFAULT_CONFIG. */
export function loadDefaultConfig(): AppConfig {
  if (_cached) return _cached

  if (existsSync(FIXTURE_PATH)) {
    try {
      _cached = JSON.parse(readFileSync(FIXTURE_PATH, 'utf8')) as AppConfig
      return _cached
    } catch {
      // Fall through to shared fallback
    }
  }

  _cached = DEFAULT_CONFIG as unknown as AppConfig
  return _cached
}
